CREATE TABLE `media_clues_sell_car_info` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `source_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '来源id',
  `source` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '来源',
  `media` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '媒体code',
  `shop_ids` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '店铺集合',
  `phone` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '号码',
  `city` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '市',
  `city_name` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '市名称',
  `car_name` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '车辆名称',
  `is_repeat` varchar(10) COLLATE utf8_unicode_ci DEFAULT '1' COMMENT '是否重复1：是，0：否',
  `score` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '分数',
  `spm` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'spm值',
  `spm_first` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'spm第一位',
  `spm_second` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'spm第二位',
  `spm_third` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'spm第三位',
  `first_boarding_time` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '首次上牌时间',
  `mileage` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '公里',
  `brand` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `series` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `model` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
  `assess_price` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '评估价格',
  `remain_place` int(11) DEFAULT '3' COMMENT '剩余抢购名额（默认最大为3）',
  `clue_type` varchar(10) CHARACTER SET utf8 DEFAULT '1' COMMENT '卖车线索类型（1:旧版线索（需指定shop_ids）2:新版线索）',
  `debug` tinyint(4) NOT NULL DEFAULT '0' COMMENT '标示该线索是否为测试数据，1表示测试数据',
  `car_name_souche` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT 'souche车型库的车辆名json',
  `alipay_user_id` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '支付宝用户ID',
  `alipay_model_id` varchar(35) CHARACTER SET utf8 DEFAULT NULL COMMENT 'alipay车主平台车型ID',
  `date_create` timestamp NULL DEFAULT NULL,
  `date_update` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `phone` (`phone`),
  KEY `city` (`city`),
  KEY `spm_first` (`spm_first`),
  KEY `is_repeat` (`is_repeat`),
  KEY `date_create` (`date_create`),
  KEY `media` (`media`),
  KEY `alipay_user_id` (`alipay_user_id`),
  KEY `alipay_model_id` (`alipay_model_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1656 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;